import { existsSync, readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import { decodeMapperSubmode, parsePonchoRom } from '../../src/core/cart-poncho/header';
import { detectConsole } from '../../src/console/detect';
import { PonchoNes } from '../../src/console/poncho-nes';
import { testRomPath } from '../rom-paths';

/**
 * Integration tests for synthetic PonchoROMs under tests/roms/poncho/.
 * These ROMs are generated by scripts in scripts/gen-poncho-rom/ and
 * committed to the repo. The test re-parses them from disk to prove
 * the writer + parser agree at the byte level, not just in memory.
 */

describe('synthetic PonchoROM: solid-bg', () => {
  const path = testRomPath('poncho/solid-bg.poncho');

  it.skipIf(!existsSync(path))('parses with the expected header and palette', () => {
    const data = new Uint8Array(readFileSync(path));
    const { header, paletteOffset, paletteByteLength } = parsePonchoRom(data);

    expect(header.title).toBe('Solid BG (synthetic)');
    expect(header.paletteCount).toBe(1);
    expect(header.prgSizeKb).toBe(1);
    expect(header.chrSizeKb).toBe(1);
    expect(header.flags.upscaledMode).toBe(false);
    expect(header.tvSystem).toBe('ntsc');
    expect(header.mapperId).toBe(1);

    // Palette entry 0 = the universal background colour the script declared.
    const palette = data.subarray(paletteOffset, paletteOffset + paletteByteLength);
    expect(palette).toEqual(new Uint8Array([0xe6, 0x3e, 0x32, 0xff]));
  });

  it.skipIf(!existsSync(path))('exists on disk at the expected size', () => {
    const data = readFileSync(path);
    // Header (64) + palette (1×4) + PRG (1024) + CHR (1024) = 2116
    expect(data.length).toBe(2116);
  });

  it.skipIf(!existsSync(path))(
    'detect → load → runFrame produces a 1024×960 frame of the BG colour',
    () => {
      const data = new Uint8Array(readFileSync(path));

      const factory = detectConsole(data);
      expect(factory).not.toBeNull();
      expect(factory!.spec.id).toBe('poncho-nes');

      const console = factory!.create();
      expect(console).toBeInstanceOf(PonchoNes);

      console.loadRom(data);
      const fb = console.runFrame();

      expect(fb.width).toBe(1024);
      expect(fb.height).toBe(960);

      // R=0xE6, G=0x3E, B=0x32, A=0xFF → ABGR-packed = 0xFF323EE6.
      const expected = 0xff323ee6;
      expect(fb.data[0]).toBe(expected);
      expect(fb.data[fb.width * fb.height - 1]).toBe(expected);
      expect(fb.data[fb.width * Math.floor(fb.height / 2) + fb.width / 2]).toBe(expected);
      // Cheap full-buffer uniformity check: any non-matching pixel?
      let mismatches = 0;
      for (let i = 0; i < fb.data.length; i++) {
        if (fb.data[i] !== expected) { mismatches++; if (mismatches > 4) break; }
      }
      expect(mismatches).toBe(0);
    },
  );
});

describe('synthetic PonchoROM: palette-write', () => {
  const path = testRomPath('poncho/palette-write.poncho');

  it.skipIf(!existsSync(path))(
    'PRG writes master-index 5 to $3F00; framebuffer becomes magenta',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      expect(factory).not.toBeNull();
      expect(factory!.spec.id).toBe('poncho-nes');

      const console = factory!.create();
      console.loadRom(data);
      const fb = console.runFrame();

      // Master palette index 5 in palette-write.ts = magenta (255, 0, 255).
      // ABGR pack of (0xFF, 0x00, 0xFF) = 0xFFFF00FF.
      const expected = 0xffff00ff;
      expect(fb.data[0]).toBe(expected);
      expect(fb.data[fb.data.length - 1]).toBe(expected);
      let mismatches = 0;
      for (let i = 0; i < fb.data.length; i++) {
        if (fb.data[i] !== expected) { mismatches++; if (mismatches > 4) break; }
      }
      expect(mismatches).toBe(0);
    },
  );
});

describe('synthetic PonchoROM: solid-tile', () => {
  const path = testRomPath('poncho/solid-tile.poncho');

  it.skipIf(!existsSync(path))(
    'PRG sets palette + nametable; full BG render path emits solid green',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      expect(factory).not.toBeNull();

      const console = factory!.create();
      console.loadRom(data);
      const fb = console.runFrame();

      // Master palette index 2 = green; ABGR-pack of (0, 255, 0) = 0xFF00FF00.
      const expected = 0xff00ff00;
      expect(fb.data[0]).toBe(expected);
      expect(fb.data[fb.data.length - 1]).toBe(expected);
      let mismatches = 0;
      for (let i = 0; i < fb.data.length; i++) {
        if (fb.data[i] !== expected) { mismatches++; if (mismatches > 4) break; }
      }
      expect(mismatches).toBe(0);
    },
  );
});

describe('synthetic PonchoROM: nmi-scroll', () => {
  const path = testRomPath('poncho/nmi-scroll.poncho');

  it.skipIf(!existsSync(path))(
    'NMI fires each frame and shifts the BG; after N frames, scroll = N-1',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      expect(factory).not.toBeNull();

      const console = factory!.create();
      console.loadRom(data);

      const red = 0xff0000ff;
      const black = 0xff000000;

      // Frame 1: NMI hasn't run before render → scroll = 0.
      let fb = console.runFrame();
      expect(fb.data[0]).toBe(red);   // tile 0 = red columns 0..31
      expect(fb.data[31]).toBe(red);
      expect(fb.data[32]).toBe(black); // tile 1 columns 32..63
      expect(fb.data[63]).toBe(black);

      // Frame 2: NMI has run once → scroll = 1.
      fb = console.runFrame();
      expect(fb.data[0]).toBe(red);
      expect(fb.data[30]).toBe(red);
      expect(fb.data[31]).toBe(black); // shift left by 1: black at col 31 now
      expect(fb.data[63]).toBe(red);   // black-tile-end becomes red-tile-start

      // Frame 9 total (7 more after the two we already ran): scroll = 8.
      // Cols 0..23 = red (last 24 cols of red tile 0); cols 24..55 = black
      // (full tile 1); 56..87 = red.
      for (let i = 0; i < 7; i++) fb = console.runFrame();
      expect(fb.data[0]).toBe(red);
      expect(fb.data[23]).toBe(red);
      expect(fb.data[24]).toBe(black);
      expect(fb.data[55]).toBe(black);
      expect(fb.data[56]).toBe(red);
    },
  );
});

describe('synthetic PonchoROM: single-sprite', () => {
  const path = testRomPath('poncho/single-sprite.poncho');

  it.skipIf(!existsSync(path))(
    'PRG installs OAM[0]; renderer paints a 32×32 red sprite at (100, 80)',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      expect(factory).not.toBeNull();

      const console = factory!.create();
      console.loadRom(data);
      const fb = console.runFrame();

      const black = 0xff000000;
      const red = 0xff0000ff;

      // Inside sprite.
      expect(fb.data[80 * 1024 + 100]).toBe(red);
      expect(fb.data[111 * 1024 + 131]).toBe(red);
      // Outside sprite.
      expect(fb.data[80 * 1024 + 99]).toBe(black);
      expect(fb.data[80 * 1024 + 132]).toBe(black);
      expect(fb.data[79 * 1024 + 100]).toBe(black);
      expect(fb.data[112 * 1024 + 100]).toBe(black);
      // Corners of the screen are background.
      expect(fb.data[0]).toBe(black);
      expect(fb.data[fb.data.length - 1]).toBe(black);

      // Exact red-pixel count = 32 × 32 = 1024.
      let red_count = 0;
      for (let i = 0; i < fb.data.length; i++) if (fb.data[i] === red) red_count++;
      expect(red_count).toBe(1024);
    },
  );
});

describe('synthetic PonchoROM: mmc1-bankswitch', () => {
  const path = testRomPath('poncho/mmc1-bankswitch.poncho');

  it.skipIf(!existsSync(path))(
    'declares MMC1-style banking variant',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const { header } = parsePonchoRom(data);
      expect(decodeMapperSubmode(header.mapperSubmode)).toEqual({
        bankingVariant: 1,
        bootMirroring: 0,
      });
      expect(header.prgSizeKb).toBe(64);
    },
  );

  it.skipIf(!existsSync(path))(
    'PRG drives MMC1 serial protocol; bank-selects 0/1/2 in turn yield distinct sentinel bytes',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      const console = factory!.create() as PonchoNes;
      console.loadRom(data);

      // PRG runs in bank 3 (the fixed bank at $C000), serial-writes 5 bits
      // to $E000 to select each of banks 0/1/2 in turn, reads $8000, and
      // stores the sentinel to zero-page. One frame is more than enough.
      console.runFrame();

      const ram = console.cpuBus.ram;
      expect(ram[0x00]).toBe(0xb0);
      expect(ram[0x01]).toBe(0xb1);
      expect(ram[0x02]).toBe(0xb2);
    },
  );
});

describe('synthetic PonchoROM: scanline-split', () => {
  const path = testRomPath('poncho/scanline-split.poncho');

  it.skipIf(!existsSync(path))(
    'declares upscaled mode + 8 KB CHR-RAM',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const { header } = parsePonchoRom(data);
      expect(header.flags.upscaledMode).toBe(true);
      expect(header.chrRamKb).toBe(8);
    },
  );

  it.skipIf(!existsSync(path))(
    'palette change after sprite-0 hit applies to scanlines below the hit only',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      const console = factory!.create() as PonchoNes;
      console.loadRom(data);

      // Frame 0: PRG sets up tile + palette + OAM. Pre-render computes
      // sprite-0 hit scanline = 32.
      console.runFrame();
      // Frame 1: visible scanlines 0..31 render with red ($3F01 = 1);
      // sprite-0 hit fires at scanline 32; PRG poll exits and writes
      // $3F01 = 2 (green); scanlines 32+ render with green.
      const fb = console.runFrame();

      const red = 0xff0000ff;
      const green = 0xff00ff00;
      const px = (y: number, x: number) => fb.data[y * 1024 + x];

      // Top — render-state captured BEFORE PRG poll exits.
      // (PRG poll exits a few CPU cycles after sprite-0 hit fires at NES
      // scanline 32 dot 1; the palette write completes within the same
      // scanline, so the render at end-of-scanline-32 picks up green.
      // We assert tolerantly: top-of-frame red, bottom-of-frame green,
      // with a small in-between window where the exact split lands.)
      expect(px(0, 0)).toBe(red);
      expect(px(0, 100)).toBe(red);
      expect(px(31, 0)).toBe(red);
      // NES scanline 31 (Poncho rows 124..127) finishes BEFORE the hit.
      expect(px(124, 0)).toBe(red);
      expect(px(127, 0)).toBe(red);

      // Bottom — palette is green by these scanlines.
      expect(px(800, 0)).toBe(green);
      expect(px(800, 500)).toBe(green);
      // Well-clear of the boundary — NES scanline 50+.
      expect(px(200, 0)).toBe(green);
    },
  );
});

describe('synthetic PonchoROM: sprite0-hit', () => {
  const path = testRomPath('poncho/sprite0-hit.poncho');

  it.skipIf(!existsSync(path))(
    'declares upscaled mode + 8 KB CHR-RAM',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const { header } = parsePonchoRom(data);
      expect(header.flags.upscaledMode).toBe(true);
      expect(header.chrRamKb).toBe(8);
    },
  );

  it.skipIf(!existsSync(path))(
    'PpuUltra.sprite0Hit becomes true after one full frame; status bit 6 readable via $2002',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      const console = factory!.create() as PonchoNes;
      console.loadRom(data);

      // Frame 0: PRG sets up tile + palette + OAM + halts.
      console.runFrame();
      // Frame 1: pre-render computes sprite0HitScanline; visible scanlines
      // set the flag at scanline 100.
      console.runFrame();

      expect(console.ppu.sprite0Hit).toBe(true);

      // Reading $2002 reflects bit 6 (and clears the vblank flag as a
      // side effect — sprite-0 hit stays set until pre-render of next
      // frame).
      const status = console.cpuBus.read(0x2002);
      expect((status & 0x40) !== 0).toBe(true);
    },
  );
});

describe('synthetic PonchoROM: sprite-8x16', () => {
  const path = testRomPath('poncho/sprite-8x16.poncho');

  it.skipIf(!existsSync(path))(
    'PRG enables 8×16 mode; sprite renders as a 32×64 block at Poncho (32, 64)..(63, 127)',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      const console = factory!.create() as PonchoNes;
      console.loadRom(data);
      console.runFrame();
      const fb = console.runFrame();

      const red = 0xff0000ff;
      const black = 0xff000000;
      const px = (y: number, x: number) => fb.data[y * 1024 + x];

      // OAM y=16 → NES y=17 (NES hardware sprite delay) → Poncho y=68.
      // 8x16 sprite spans Poncho rows 68..131.
      expect(px(68, 32)).toBe(red);
      expect(px(68, 63)).toBe(red);
      expect(px(99, 32)).toBe(red);    // last row of top half
      expect(px(100, 32)).toBe(red);   // first row of bottom half
      expect(px(131, 32)).toBe(red);   // bottom of sprite
      // Just outside.
      expect(px(67, 48)).toBe(black);  // one row above
      expect(px(132, 48)).toBe(black); // one row below the 8×16 block
    },
  );
});

describe('synthetic PonchoROM: upscaled-sprite', () => {
  const path = testRomPath('poncho/upscaled-sprite.poncho');

  it.skipIf(!existsSync(path))(
    'declares upscaled mode + 8 KB CHR-RAM',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const { header } = parsePonchoRom(data);
      expect(header.flags.upscaledMode).toBe(true);
      expect(header.chrRamKb).toBe(8);
    },
  );

  it.skipIf(!existsSync(path))(
    'PRG places one NES sprite at (8, 16) tile 0; render shows 32×32 red block at Poncho (32, 64)',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      const console = factory!.create() as PonchoNes;
      console.loadRom(data);

      console.runFrame();
      const fb = console.runFrame();

      const red = 0xff0000ff;
      const black = 0xff000000;
      const px = (y: number, x: number) => fb.data[y * 1024 + x];

      // OAM y=16 → NES y=17 → Poncho y=68. Sprite spans Poncho (32..63, 68..99).
      expect(px(68, 32)).toBe(red);
      expect(px(68, 63)).toBe(red);
      expect(px(99, 32)).toBe(red);
      expect(px(99, 63)).toBe(red);
      expect(px(80, 48)).toBe(red); // mid-sprite
      // Outside the sprite — should be BG (black).
      expect(px(67, 48)).toBe(black); // one row above
      expect(px(100, 48)).toBe(black); // one row below
      expect(px(80, 31)).toBe(black); // one col left
      expect(px(80, 64)).toBe(black); // one col right
    },
  );

  it.skipIf(!existsSync(path))(
    'OAM contains the NES-shape sprite at offsets [0..3]',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      const console = factory!.create() as PonchoNes;
      console.loadRom(data);
      console.runFrame();

      const oam = console.ppu.oamRam;
      expect(oam[0]).toBe(16);    // y
      expect(oam[1]).toBe(0);     // tile
      expect(oam[2]).toBe(0x01);  // attr (sub-palette 1)
      expect(oam[3]).toBe(8);     // x
    },
  );
});

describe('synthetic PonchoROM: upscaled-chr', () => {
  const path = testRomPath('poncho/upscaled-chr.poncho');

  it.skipIf(!existsSync(path))(
    'declares upscaled mode + 8 KB CHR-RAM',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const { header } = parsePonchoRom(data);
      expect(header.flags.upscaledMode).toBe(true);
      expect(header.chrRamKb).toBe(8);
      expect(header.chrSizeKb).toBe(0);
    },
  );

  it.skipIf(!existsSync(path))(
    'PRG uploads a column-stripe NES tile via $2007; render shows 4-px red stripes every 32 px',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      const console = factory!.create() as PonchoNes;
      console.loadRom(data);

      // Two frames: PRG runs in the first; second frame renders the
      // populated CHR-RAM + palette.
      console.runFrame();
      const fb = console.runFrame();

      // ABGR pack — (R=255, G=0, B=0, A=255) = 0xFF0000FF.
      const red = 0xff0000ff;
      const black = 0xff000000;

      // Top scan-line — repeating 4-px red stripes every 32 px.
      expect(fb.data[0]).toBe(red);
      expect(fb.data[1]).toBe(red);
      expect(fb.data[2]).toBe(red);
      expect(fb.data[3]).toBe(red);
      expect(fb.data[4]).toBe(black);
      expect(fb.data[31]).toBe(black);
      expect(fb.data[32]).toBe(red);
      expect(fb.data[35]).toBe(red);
      expect(fb.data[36]).toBe(black);

      // Same pattern holds at row 100 and row 800.
      const row = (y: number, x: number) => fb.data[y * 1024 + x];
      expect(row(100, 0)).toBe(red);
      expect(row(100, 5)).toBe(black);
      expect(row(800, 32)).toBe(red);
    },
  );

  it.skipIf(!existsSync(path))(
    'CHR-RAM ppuWrite via the mapper persists; ppuRead returns the same byte',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      const console = factory!.create() as PonchoNes;
      console.loadRom(data);
      console.runFrame();

      // After PRG runs, mapper.ppuRead($0000..$0007) should return 0x80
      // (the plane-0 bytes the loop wrote).
      const mapper = console.cartridge!.mapper;
      for (let i = 0; i < 8; i++) {
        expect(mapper.ppuRead(i)).toBe(0x80);
      }
      // Plane 1 (offsets $0008..$000F) is zero.
      for (let i = 8; i < 16; i++) {
        expect(mapper.ppuRead(i)).toBe(0x00);
      }
    },
  );
});

describe('synthetic PonchoROM: multi-nametable', () => {
  const path = testRomPath('poncho/multi-nametable.poncho');

  it.skipIf(!existsSync(path))(
    'declares NROM banking + vertical mirroring',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const { header } = parsePonchoRom(data);
      expect(header.flags.upscaledMode).toBe(false);
      expect(decodeMapperSubmode(header.mapperSubmode)).toEqual({
        bankingVariant: 0,
        bootMirroring: 1,
      });
    },
  );

  it.skipIf(!existsSync(path))(
    'PRG fills NT0 with tile 0 (red) and NT1 with tile 1 (green); base NT = 1 → screen is green',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      const console = factory!.create() as PonchoNes;
      console.loadRom(data);

      // Two frames: first one runs PRG (palette + nametable fills + base
      // NT switch), second one renders the now-fully-configured state.
      console.runFrame();
      const fb = console.runFrame();

      // ABGR pack of (R=0, G=255, B=0, A=255) = 0xFF00FF00.
      const green = 0xff00ff00;
      // Sample several screen-area pixels.
      expect(fb.data[0 * 1024 + 0]).toBe(green);
      expect(fb.data[100 * 1024 + 100]).toBe(green);
      expect(fb.data[fb.data.length - 1]).toBe(green);

      // And the universal-BG colour landed at $3F00 = master[0] = black.
      expect(console.ppu.paletteRam[0]).toBe(0);
    },
  );

  it.skipIf(!existsSync(path))(
    'mapper.mirroring() is vertical and PpuUltra resolves NT1 to physical page 1',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      const console = factory!.create() as PonchoNes;
      console.loadRom(data);
      expect(console.cartridge!.mapper.mirroring()).toBe('vertical');

      // After PRG runs, the two physical NT pages should hold distinct
      // tile bytes: page 0 = tile 0, page 1 = tile 1.
      console.runFrame();
      const ntRam = console.ppu.nametableRam;
      // First tile cell of physical page 0 was written via $2000.
      expect(ntRam[0x000]).toBe(0);
      // First tile cell of physical page 1 was written via $2400 — under
      // vertical mirroring NT1 → physical 1 → offset 0x400.
      expect(ntRam[0x400]).toBe(1);
    },
  );
});

describe('synthetic PonchoROM: uxrom-bankswitch', () => {
  const path = testRomPath('poncho/uxrom-bankswitch.poncho');

  it.skipIf(!existsSync(path))(
    'declares UxROM-style banking variant + vertical boot mirroring',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const { header } = parsePonchoRom(data);
      expect(header.flags.upscaledMode).toBe(true);
      expect(decodeMapperSubmode(header.mapperSubmode)).toEqual({
        bankingVariant: 2,
        bootMirroring: 1,
      });
      expect(header.prgSizeKb).toBe(64);
    },
  );

  it.skipIf(!existsSync(path))(
    'PRG bank-selects 0/1/2 in turn; reads at $8000 see distinct sentinels',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      expect(factory).not.toBeNull();
      const console = factory!.create();
      expect(console).toBeInstanceOf(PonchoNes);
      console.loadRom(data);

      // The PRG executes from the fixed last bank ($C000), bank-selects
      // 0/1/2 in sequence and stores each bank's sentinel byte to zero
      // page $00/$01/$02. One frame is plenty for those ~25 cycles.
      console.runFrame();

      const ram = (console as PonchoNes).cpuBus.ram;
      expect(ram[0x00]).toBe(0xa0);
      expect(ram[0x01]).toBe(0xa1);
      expect(ram[0x02]).toBe(0xa2);
    },
  );

  it.skipIf(!existsSync(path))(
    'mapper.mirroring() reflects the encoded boot mirroring (vertical)',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      const console = factory!.create() as PonchoNes;
      console.loadRom(data);
      expect(console.cartridge!.mapper.mirroring()).toBe('vertical');
    },
  );
});
