import { existsSync, readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import { parsePonchoRom } from '../../src/core/cart-poncho/header';
import { detectConsole } from '../../src/console/detect';
import { PonchoNes } from '../../src/console/poncho-nes';
import { testRomPath } from '../rom-paths';

/**
 * Integration tests for synthetic PonchoROMs under tests/roms/poncho/.
 * These ROMs are generated by scripts in scripts/gen-poncho-rom/ and
 * committed to the repo. The test re-parses them from disk to prove
 * the writer + parser agree at the byte level, not just in memory.
 */

describe('synthetic PonchoROM: solid-bg', () => {
  const path = testRomPath('poncho/solid-bg.poncho');

  it.skipIf(!existsSync(path))('parses with the expected header and palette', () => {
    const data = new Uint8Array(readFileSync(path));
    const { header, paletteOffset, paletteByteLength } = parsePonchoRom(data);

    expect(header.title).toBe('Solid BG (synthetic)');
    expect(header.paletteCount).toBe(1);
    expect(header.prgSizeKb).toBe(1);
    expect(header.chrSizeKb).toBe(1);
    expect(header.flags.upscaledMode).toBe(false);
    expect(header.tvSystem).toBe('ntsc');
    expect(header.mapperId).toBe(1);

    // Palette entry 0 = the universal background colour the script declared.
    const palette = data.subarray(paletteOffset, paletteOffset + paletteByteLength);
    expect(palette).toEqual(new Uint8Array([0xe6, 0x3e, 0x32, 0xff]));
  });

  it.skipIf(!existsSync(path))('exists on disk at the expected size', () => {
    const data = readFileSync(path);
    // Header (64) + palette (1×4) + PRG (1024) + CHR (1024) = 2116
    expect(data.length).toBe(2116);
  });

  it.skipIf(!existsSync(path))(
    'detect → load → runFrame produces a 1024×960 frame of the BG colour',
    () => {
      const data = new Uint8Array(readFileSync(path));

      const factory = detectConsole(data);
      expect(factory).not.toBeNull();
      expect(factory!.spec.id).toBe('poncho-nes');

      const console = factory!.create();
      expect(console).toBeInstanceOf(PonchoNes);

      console.loadRom(data);
      const fb = console.runFrame();

      expect(fb.width).toBe(1024);
      expect(fb.height).toBe(960);

      // R=0xE6, G=0x3E, B=0x32, A=0xFF → ABGR-packed = 0xFF323EE6.
      const expected = 0xff323ee6;
      expect(fb.data[0]).toBe(expected);
      expect(fb.data[fb.width * fb.height - 1]).toBe(expected);
      expect(fb.data[fb.width * Math.floor(fb.height / 2) + fb.width / 2]).toBe(expected);
      // Cheap full-buffer uniformity check: any non-matching pixel?
      let mismatches = 0;
      for (let i = 0; i < fb.data.length; i++) {
        if (fb.data[i] !== expected) { mismatches++; if (mismatches > 4) break; }
      }
      expect(mismatches).toBe(0);
    },
  );
});

describe('synthetic PonchoROM: palette-write', () => {
  const path = testRomPath('poncho/palette-write.poncho');

  it.skipIf(!existsSync(path))(
    'PRG writes master-index 5 to $3F00; framebuffer becomes magenta',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      expect(factory).not.toBeNull();
      expect(factory!.spec.id).toBe('poncho-nes');

      const console = factory!.create();
      console.loadRom(data);
      const fb = console.runFrame();

      // Master palette index 5 in palette-write.ts = magenta (255, 0, 255).
      // ABGR pack of (0xFF, 0x00, 0xFF) = 0xFFFF00FF.
      const expected = 0xffff00ff;
      expect(fb.data[0]).toBe(expected);
      expect(fb.data[fb.data.length - 1]).toBe(expected);
      let mismatches = 0;
      for (let i = 0; i < fb.data.length; i++) {
        if (fb.data[i] !== expected) { mismatches++; if (mismatches > 4) break; }
      }
      expect(mismatches).toBe(0);
    },
  );
});

describe('synthetic PonchoROM: solid-tile', () => {
  const path = testRomPath('poncho/solid-tile.poncho');

  it.skipIf(!existsSync(path))(
    'PRG sets palette + nametable; full BG render path emits solid green',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      expect(factory).not.toBeNull();

      const console = factory!.create();
      console.loadRom(data);
      const fb = console.runFrame();

      // Master palette index 2 = green; ABGR-pack of (0, 255, 0) = 0xFF00FF00.
      const expected = 0xff00ff00;
      expect(fb.data[0]).toBe(expected);
      expect(fb.data[fb.data.length - 1]).toBe(expected);
      let mismatches = 0;
      for (let i = 0; i < fb.data.length; i++) {
        if (fb.data[i] !== expected) { mismatches++; if (mismatches > 4) break; }
      }
      expect(mismatches).toBe(0);
    },
  );
});

describe('synthetic PonchoROM: nmi-scroll', () => {
  const path = testRomPath('poncho/nmi-scroll.poncho');

  it.skipIf(!existsSync(path))(
    'NMI fires each frame and shifts the BG; after N frames, scroll = N-1',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      expect(factory).not.toBeNull();

      const console = factory!.create();
      console.loadRom(data);

      const red = 0xff0000ff;
      const black = 0xff000000;

      // Frame 1: NMI hasn't run before render → scroll = 0.
      let fb = console.runFrame();
      expect(fb.data[0]).toBe(red);   // tile 0 = red columns 0..31
      expect(fb.data[31]).toBe(red);
      expect(fb.data[32]).toBe(black); // tile 1 columns 32..63
      expect(fb.data[63]).toBe(black);

      // Frame 2: NMI has run once → scroll = 1.
      fb = console.runFrame();
      expect(fb.data[0]).toBe(red);
      expect(fb.data[30]).toBe(red);
      expect(fb.data[31]).toBe(black); // shift left by 1: black at col 31 now
      expect(fb.data[63]).toBe(red);   // black-tile-end becomes red-tile-start

      // Frame 9 total (7 more after the two we already ran): scroll = 8.
      // Cols 0..23 = red (last 24 cols of red tile 0); cols 24..55 = black
      // (full tile 1); 56..87 = red.
      for (let i = 0; i < 7; i++) fb = console.runFrame();
      expect(fb.data[0]).toBe(red);
      expect(fb.data[23]).toBe(red);
      expect(fb.data[24]).toBe(black);
      expect(fb.data[55]).toBe(black);
      expect(fb.data[56]).toBe(red);
    },
  );
});

describe('synthetic PonchoROM: single-sprite', () => {
  const path = testRomPath('poncho/single-sprite.poncho');

  it.skipIf(!existsSync(path))(
    'PRG installs OAM[0]; renderer paints a 32×32 red sprite at (100, 80)',
    () => {
      const data = new Uint8Array(readFileSync(path));
      const factory = detectConsole(data);
      expect(factory).not.toBeNull();

      const console = factory!.create();
      console.loadRom(data);
      const fb = console.runFrame();

      const black = 0xff000000;
      const red = 0xff0000ff;

      // Inside sprite.
      expect(fb.data[80 * 1024 + 100]).toBe(red);
      expect(fb.data[111 * 1024 + 131]).toBe(red);
      // Outside sprite.
      expect(fb.data[80 * 1024 + 99]).toBe(black);
      expect(fb.data[80 * 1024 + 132]).toBe(black);
      expect(fb.data[79 * 1024 + 100]).toBe(black);
      expect(fb.data[112 * 1024 + 100]).toBe(black);
      // Corners of the screen are background.
      expect(fb.data[0]).toBe(black);
      expect(fb.data[fb.data.length - 1]).toBe(black);

      // Exact red-pixel count = 32 × 32 = 1024.
      let red_count = 0;
      for (let i = 0; i < fb.data.length; i++) if (fb.data[i] === red) red_count++;
      expect(red_count).toBe(1024);
    },
  );
});
